name: 'Before test'
description: 'Before test'
runs:
  using: "composite"
  steps:
    - name: Cache Maven # From https://github.com/actions/cache/blob/main/examples.md
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Warm-up mvn cache
      shell: bash
      run: |
        mvn --version
        mvn clean verify
    - name: Prepare tests
      shell: bash
      run: |
        sudo sysctl -w vm.max_map_count=262144
        sudo mkdir -p /opt/app
        sudo cp arlas-tests/src/test/resources/arlas-test.pem /opt/app/