name: Run Trivy - Hadolint- Dockle
run-name: Run Trivy - Hadolint- Dockle - Vulnerability Scan

on:
  push:
  schedule:
    # At 05:15 UTC on day-of-month 2
    - cron: '15 5 2 * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        failure-threshold: "error"
        dockerfile: "Dockerfile"
    - name: Build an image from Dockerfile
      run: |
        docker build -t docker.io/gisaia/arlas-server:${{ github.sha }} .
    - name: Run Dockle
      uses: erzz/dockle-action@v1
      with:
        image: 'docker.io/gisaia/arlas-server:${{ github.sha }}'
        exit-code: 1
        failure-threshold: fatal
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
      with:
        image-ref: 'docker.io/gisaia/arlas-server:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        timeout: '10m'
        ignore-unfixed: false
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        trivyignores: .github/workflows/.trivyignore
    - name: Notify Google Chat
      if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
      uses: SimonScholz/google-chat-action@main
      with:
        webhookUrl: '${{ secrets.GOOGLE_CHAT_SCAN_CHANEL }}'
        jobStatus: '${{ job.status }}'
        title: 'Trivy Scan on ARLAS-server'
